### ISSUE TITLE
Kontakt, co na APO

### ISSUE THREAD

**Issue by MatthewRock** [MatthewRock/apo#2]
Hej, daj swojego maila(by boty nie łowiły, to możesz napisać po polsku ;P)
Co mamy na następne APO?

**Comment by PawelPelczar** [comment]
pawel[kropka]p[kropka]pelczar[at]gmail[kropka]com

Następny do oddania mamy już pełen opis przypadków użycia wraz ze słownikiem. Prace są daleko posunięte, jutro wypchnę na gita.

**Comment by Navvroth** [comment]
Paweł będziesz jutro na uczelni ?

**Comment by PawelPelczar** [comment]
W dniu 2016-01-07 o 23:43, Navvroth pisze:

**Comment by MatthewRock** [comment]
Ja się dołącze - co mamy zrobić na wtorek? :D

W dniu 8 stycznia 2016 00:35 użytkownik Paweł Pelczar <
notifications@github.com> napisał:

**Comment by PawelPelczar** [comment]
"Zapisanie projektowego diagramu klas

Termin i sposób oddania produktu: 11.01.2016, 23:59, Wiki"

Cytat za edumatic.amu.edu.pl/

W skrócie- projektowy diagram klas tak, jak to było opisywane na 
zajęciach i wykładach.

W dniu 2016-01-08 o 00:36, MatthewRock pisze:
